# Generated by Django 3.1.7 on 2021-03-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_type',
            field=models.CharField(choices=[('Куплю', 'buy'), ('Продам', 'sell'), ('Отдам даром', 'give_free')],
                                   max_length=30),
        ),
        migrations.CreateModel(
            name='CommentAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                          related_name='comments_ads',
                                          to='spectrum.ads')),
            ],
        ),
    ]
